FROM runpod/pytorch:2.3.1-py3.10-cuda12.1.1-devel

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY worker.py .

CMD ["celery", "-A", "worker", "worker", "--loglevel=info", "--concurrency=1"]
